# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: GitHub CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  - cron: '0 */8 * * *'

jobs:
  install_dependencies:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: |
        npm ci

  jest:

    runs-on: ubuntu-latest
    needs: install_dependencies

    strategy:
      matrix:
        node: [14]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'npm'
    - run: |
        npm ci
        npm test

  cypress:

    runs-on: ubuntu-latest
    needs: jest

    strategy:
      matrix:
        node: [14]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          node-version: ${{ matrix.node }}
          browser: chrome
          build: npm ci
          start: npm start
          wait-on: "http://localhost:3000"          


  build_deploy: # builds the app and deploys it to gh-pages
    runs-on: ubuntu-latest
    needs: cypress

    strategy:
      matrix:
        node: [14]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: node -v
    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Build and Deploy
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: |
          npm ci
          npm run build --if-present
      
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
